---
- hosts: db_servers, web_servers
  gather_facts: false
  tasks:
    - name: Wait 60 seconds for target connection to become reachable/usable
      ansible.builtin.wait_for_connection:
        timeout: 60

- import_playbook: deploy_database.yaml
- import_playbook: deploy_webserver.yaml