---
- name: Install pip
  become: true
  ansible.builtin.apt: 
    name: python3-pip
    state: latest

- name: Install PyMySQL
  become: true
  pip:
    name: PyMySQL
    state: latest

- name: Install Mariadb
  become: true
  ansible.builtin.apt:
    name: mariadb-server
    state: latest
    update_cache: true

- name: Save root password in .my.cnf
  become: true
  template:
    src: root_cnf.cnf
    dest: /root/.my.cnf
    owner: root
    mode: '0600'

- name: Set password for root user
  become: true
  mysql_user:
    name: "root"
    password: "root"
    priv: '*.*:ALL,GRANT'
    host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Create admin user
  become: true
  mysql_user:
    name: admin
    password: password
    priv: '*.*:ALL'
    state: present    

- name: Set up database
  become: true
  mysql_db:
    name: github_stats
    state: present

- name: Create table
  become: true
  mysql_query:
    login_db: github_stats
    query: CREATE TABLE github_stats.scd_table (
      username VARCHAR(255),
      no_commits INT,
      avatar_url VARCHAR(255),
      html_url VARCHAR(255),
      UNIQUE (username)
      )

- name: Create table
  become: true
  mysql_query:
    login_db: github_stats
    query: CREATE TABLE github_stats.st2_table (
      username VARCHAR(255),
      no_commits INT,
      avatar_url VARCHAR(255),
      html_url VARCHAR(255),
      UNIQUE (username)
      )

- name: Copy script to VM
  become: true
  copy:
    src: update_db.sh
    dest: /home/github_scrape

- name: Copy service file to VM
  become: true
  copy:
    src: update_db.service
    dest: /etc/systemd/system

- name: Start script as service
  become: true
  command: systemctl start update_db.service

- name: Enable service start on boot
  become: true
  command: systemctl enable update_db.service
