---
- name: Install Apache2 and PHP and packages
  become: true
  ansible.builtin.apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
    state: latest
    update_cache: true

- name: Copy Virtual Host file
  become: true
  ansible.builtin.copy:
    src: webserver.conf
    dest: /etc/apache2/sites-available

- name: Prioritise index.php over index.html
  become: true
  lineinfile:
      path: /etc/apache2/mods-enabled/dir.conf
      regexp: '^(.*)DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm(.*)$'
      line: 'DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm'
      backrefs: yes
  
- name: Enable new site
  become: true
  ansible.builtin.command: a2ensite webserver

- name: Disable default site
  become: true
  ansible.builtin.command: a2dissite 000-default 

- name: Create web directory
  become: true
  ansible.builtin.file:
    path: /var/www/myWeb
    state: directory

- name: Copy web pages to site
  become: true
  copy:
    src: '{{item}}'
    dest: '/var/www/myWeb'
  loop:
    - index.html
    - SCD-Openstack-Utils.php
    - st2-cloud-pack.php

- name: Reload Apache2 Service
  become: true
  command: systemctl reload apache2.service

- name: Replace PHP local host with fip
  become: true
  replace:
    path: /var/www/myWeb/SCD-Openstack-Utils.php
    regexp: 'localhost'
    replace: '{{ db_ip }}'

- name: Replace PHP local host with fip
  become: true
  replace:
    path: /var/www/myWeb/st2-cloud-pack.php
    regexp: 'localhost'
    replace: '{{ db_ip }}'
